controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\CoreAlbums;
use app\models\CoreAuthors;
use app\models\CoreCategory;
use app\models\CoreNews;
use app\models\CoreSongs;
use app\models\CoreTags;
use app\models\Image;
use app\models\Users;
use dektrium\user\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'signup', 'logout'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup', 'logout'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionIndex()
    {
//        if (!Yii::$app->user->isGuest) {
//            return $this->render('index');
//        }

        $model = new User();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->render('index');
    }

    public function actionSearch()
    {
        $song = '';
        return $this->render('search', ['song' => $song]);
    }

    public function actionDebug()
    {
        return $this->render('debug');

    }

    /**
     * @return string
     */
    public function actionRegistration()
    {

        $model = new Users();
        if ((Yii::$app->request->post())) {
            return $this->render('index');
        }

        return $this->render('registration', ['model' => $model]);
    }

    public function actionNews()
    {
        return $this->render('news');
    }

    public function actionOptions()
    {
        return $this->render('options');
    }

    public function actionAddNews()
    {
        $data = $this->findData();

        return $this->render('addNews', ['data' => $data]);
    }

    public function actionAddAuthor()
    {
        $data = $this->findData();

        return $this->render('addAuthor', ['data' => $data]);
    }

    public function actionAddCategory()
    {
        return $this->render('addCategory');
    }

    public function actionAddAlbum()
    {
        $data = [];
        $songsDb = CoreSongs::findAll(['id_album'=>0]);
        if ($songsDb) {
            foreach ($songsDb as $value) {
                $data['songs-list'][$value->song_name] = $value->song_name;
                $data['songs-opt']['disabled'] = false;
            }
        } else {
            $data['songs-list'] = null;
            $data['songs-opt']['disabled'] = true;
        }
        return $this->render('addAlbum', ['data' => $data]);
    }


    public function actionDelete()
    {
        $data = $this->findData();

        return $this->render('delete',['data'=>$data]);
    }

    public function findData(){
        $data = [];
        $categoryDb = CoreCategory::find()->all();
        if ($categoryDb) {
            foreach ($categoryDb as $value) {
                $data['category-list'][$value->category_name] = $value->category_name;
                $data['category-opt']['disabled'] = false;
            }
        } else {
            $data['category-list'] = null;
            $data['category-opt']['disabled'] = true;
        }
        $newsDb = CoreNews::find()->all();
        if ($newsDb) {
            foreach ($newsDb as $value) {
                $data['news-list'][$value->title] = $value->title;
                $data['news-opt']['disabled'] = false;
            }
        } else {
            $data['news-list'] = null;
            $data['news-opt']['disabled'] = true;
        }
        $albumsDb = CoreAlbums::find()->all();
        if ($albumsDb) {
            foreach ($albumsDb as $value) {
                $data['album-list'][$value->name_album] = $value->name_album;
                $data['album-opt']['disabled'] = false;
            }
        } else {
            $data['album-list'] = null;
            $data['album-opt']['disabled'] = true;
        }
        $songsDb = CoreSongs::find()->all();
        if ($songsDb) {
            foreach ($songsDb as $value) {
                $data['songs-list'][$value->song_name] = $value->song_name;
                $data['songs-opt']['disabled'] = false;
            }
        } else {
            $data['songs-list'] = null;
            $data['songs-opt']['disabled'] = true;
        }
        $tagsDb = CoreTags::find()->all();
        if ($tagsDb) {
            foreach ($tagsDb as $value) {
                $data['tags-list'][$value->name_tag] = $value->name_tag;
            }
        } else {
            $data['tags-list'] = null;
        }
        return $data;
    }

    public function actionUserCabinet()
    {
        return $this->render('userCabinet');
    }

    public function actionUploadSong()
    {

        $post = Yii::$app->request->post();
        return $this->render('uploadSong', ['post' => $post]);
    }
}

views/layouts/footer.php
<?php
/**
 * Created by PhpStorm.
 * User: lossless
 * Date: 2/3/17
 * Time: 21:26
 */
?>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Music Web Admin <?= date('Y') ?></p>
    </div>
</footer>

views/layouts/header.php
<?php
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\helpers\Url;
NavBar::begin([
    'brandLabel' => 'Music Web Admin',
    'brandUrl' => Url::home(),
    'options' => [
        'class' => 'navbar-inverse navbar-fixed-top',
    ],
]);
echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'items' => [
//        ['label' => 'Registration', 'url' => ['site/registration'],true],
//        Yii::$app->user->isGuest ? (
//        ""
//        ) : (
//            ['label' => 'Cabinet', 'url' => ['site/userCabinet'],true]
//        ),
//        Yii::$app->user->isGuest ? (
//        ['label' => 'Login', 'url' => ['site/login']]
//        ) : (
//            '<li>'
//            . Html::beginForm(['site/logout'], 'post')
//            . Html::submitButton(
//                'Logout (' . Yii::$app->user->identity->username . ')',
//                ['class' => 'btn btn-link logout']
//            )
//            . Html::endForm()
//            . '</li>'
//        ),
    ],
]);
NavBar::end();


?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use \yii\bootstrap\ActiveForm;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/images/pic.png" type="image/png">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php $this->beginContent('@app/views/layouts/header.php'); ?>
    <!-- You may need to put some content here -->
    <?php $this->endContent(); ?>
    <div class="container main-container">
        <div class="left-nav-menu col-xs-3">
            <div>
                <?php ActiveForm::begin(['id' => 'h-search', 'method' => 'post', 'action' => '/site/search']) ?>
                <span class="glyphicon glyphicon-search"></span>
                <?= Html::submitButton('Search', ['class' => 'left-nav-buttons']); ?>
                <?php ActiveForm::end(); ?>
            </div>
            <div>
                <?php ActiveForm::begin(['id' => 'h-news', 'method' => 'post', 'action' => '/site/news']) ?>
                <span class="glyphicon glyphicon-fire"></span>
                <?= Html::submitButton('News', ['class' => 'left-nav-buttons','style'=>'text-decoration:line-through','disabled'=>'disabled']); ?>
                <?php ActiveForm::end(); ?>
            </div>
            <div>
                <?php ActiveForm::begin(['id' => 'h-up-song', 'method' => 'post', 'action' => '/site/upload-song']) ?>
                <span class="glyphicon glyphicon-cloud-upload"></span>
                <?= Html::submitButton('Upload song', ['class' => 'left-nav-buttons']); ?>
                <?php ActiveForm::end(); ?>
            </div>
            <div>
                <?php ActiveForm::begin(['id' => 'h-up-album', 'method' => 'post', 'action' => '/site/add-album']) ?>
                <span class="glyphicon glyphicon-cloud-upload"></span>
                <?= Html::submitButton('Create album', ['class' => 'left-nav-buttons']); ?>
                <?php ActiveForm::end(); ?>
            </div>
            <div>
                <?php ActiveForm::begin(['id' => 'h-up-author', 'method' => 'post', 'action' => '/site/add-author']) ?>
                <span class="glyphicon glyphicon-cloud-upload"></span>
                <?= Html::submitButton('Create author', ['class' => 'left-nav-buttons']); ?>
                <?php ActiveForm::end(); ?>
            </div>
            <div>
                <?php ActiveForm::begin(['id' => 'h-up-category', 'method' => 'post', 'action' => '/site/add-category']) ?>
                <span class="glyphicon glyphicon-cloud-upload"></span>
                <?= Html::submitButton('Create category', ['class' => 'left-nav-buttons','style'=>'text-decoration:line-through','disabled'=>'disabled']); ?>
                <?php ActiveForm::end(); ?>
            </div>
            <div>
                <?php ActiveForm::begin(['id' => 'h-up-news', 'method' => 'post', 'action' => '/site/add-news']) ?>
                <span class="glyphicon glyphicon-cloud-upload"></span>
                <?= Html::submitButton('Create news', ['class' => 'left-nav-buttons','style'=>'text-decoration:line-through','disabled'=>'disabled']); ?>
                <?php ActiveForm::end(); ?>
            </div>
            <div>
                <?php ActiveForm::begin(['id' => 'h-delete', 'method' => 'post', 'action' => '/site/delete']) ?>
                <span class="glyphicon glyphicon-floppy-remove"></span>
                <?= Html::submitButton('Delete', ['class' => 'left-nav-buttons']); ?>
                <?php ActiveForm::end(); ?>
            </div>
            <div>
                <?php ActiveForm::begin(['id' => 'h-debug', 'method' => 'post', 'action' => '/site/debug']) ?>
                <span class="glyphicon glyphicon-compressed"></span>
                <?= Html::submitButton('Debug', ['class' => 'left-nav-buttons']); ?>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <div class="right-side-cont col-xs-9">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= $content ?>
        </div>
    </div>
    <?php $this->beginContent('@app/views/layouts/footer.php'); ?>
    <!-- You may need to put some content here -->
    <?php $this->endContent(); ?>
</div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>