controllers/SaveController.php
<?php

namespace app\controllers;

use app\models\CoreAlbums;
use app\models\CoreAuthors;
use app\models\CoreCategory;
use Yii;
use app\models\CoreNews;
use yii\helpers\Json;
use \yii\web\Controller;
use app\models\CoreSongs;
class SaveController extends Controller
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionSaveSong(){
        $song = new CoreSongs();
        $result = $song->uploadSongs($_FILES);
        echo Json::encode($result);
        exit;
    }

    public function actionSaveNews(){
        $post = Yii::$app->request->post();
        $song = new CoreNews();
        $result = $song->uploadNews($post);
        echo Json::encode($result);
        exit;
    }

    public function actionSaveAuthor(){
        $post = Yii::$app->request->post();
        $song = new CoreAuthors();
        $result = $song->createAuthor($post);
        echo Json::encode($result);
    }

    public function actionSaveCategory(){
        $post = Yii::$app->request->post();
        $song = new CoreCategory();
        $result = $song->createCategory($post);
        echo Json::encode($result);
        exit;
    }

    public function actionSaveAlbum(){
        $post = Yii::$app->request->post();
        $song = new CoreAlbums();
        $result = $song->createAlbum($post);
        echo Json::encode($result);
        exit;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\CoreAlbums;
use app\models\CoreAuthors;
use app\models\CoreCategory;
use app\models\CoreNews;
use app\models\CoreSongs;
use app\models\CoreTags;
use app\models\Image;
use app\models\Users;
use dektrium\user\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'signup', 'logout'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup', 'logout'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionIndex()
    {
//        if (!Yii::$app->user->isGuest) {
//            return $this->render('index');
//        }

        $model = new User();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->render('index');
    }

    public function actionSearch()
    {
        $song = '';
        return $this->render('search', ['song' => $song]);
    }

    public function actionDebug()
    {
        return $this->render('debug');

    }

    /**
     * @return string
     */
    public function actionRegistration()
    {

        $model = new Users();
        if ((Yii::$app->request->post())) {
            return $this->render('index');
        }

        return $this->render('registration', ['model' => $model]);
    }

    public function actionNews()
    {
        return $this->render('news');
    }

    public function actionOptions()
    {
        return $this->render('options');
    }

    public function actionAddNews()
    {
        $data = $this->findData();

        return $this->render('addNews', ['data' => $data]);
    }

    public function actionAddAuthor()
    {
        $data = $this->findData();

        return $this->render('addAuthor', ['data' => $data]);
    }

    public function actionAddCategory()
    {
        return $this->render('addCategory');
    }

    public function actionAddAlbum()
    {
        $data = [];
        $songsDb = CoreSongs::findAll(['id_album'=>0]);
        if ($songsDb) {
            foreach ($songsDb as $value) {
                $data['songs-list'][$value->song_name] = $value->song_name;
                $data['songs-opt']['disabled'] = false;
            }
        } else {
            $data['songs-list'] = null;
            $data['songs-opt']['disabled'] = true;
        }
        return $this->render('addAlbum', ['data' => $data]);
    }


    public function actionDelete()
    {
        $data = $this->findData();

        return $this->render('delete',['data'=>$data]);
    }

    public function findData(){
        $data = [];
        $categoryDb = CoreCategory::find()->all();
        if ($categoryDb) {
            foreach ($categoryDb as $value) {
                $data['category-list'][$value->category_name] = $value->category_name;
                $data['category-opt']['disabled'] = false;
            }
        } else {
            $data['category-list'] = null;
            $data['category-opt']['disabled'] = true;
        }
        $newsDb = CoreNews::find()->all();
        if ($newsDb) {
            foreach ($newsDb as $value) {
                $data['news-list'][$value->title] = $value->title;
                $data['news-opt']['disabled'] = false;
            }
        } else {
            $data['news-list'] = null;
            $data['news-opt']['disabled'] = true;
        }
        $albumsDb = CoreAlbums::find()->all();
        if ($albumsDb) {
            foreach ($albumsDb as $value) {
                $data['album-list'][$value->name_album] = $value->name_album;
                $data['album-opt']['disabled'] = false;
            }
        } else {
            $data['album-list'] = null;
            $data['album-opt']['disabled'] = true;
        }
        $songsDb = CoreSongs::find()->all();
        if ($songsDb) {
            foreach ($songsDb as $value) {
                $data['songs-list'][$value->song_name] = $value->song_name;
                $data['songs-opt']['disabled'] = false;
            }
        } else {
            $data['songs-list'] = null;
            $data['songs-opt']['disabled'] = true;
        }
        $tagsDb = CoreTags::find()->all();
        if ($tagsDb) {
            foreach ($tagsDb as $value) {
                $data['tags-list'][$value->name_tag] = $value->name_tag;
            }
        } else {
            $data['tags-list'] = null;
        }
        return $data;
    }

    public function actionUserCabinet()
    {
        return $this->render('userCabinet');
    }

    public function actionUploadSong()
    {

        $post = Yii::$app->request->post();
        return $this->render('uploadSong', ['post' => $post]);
    }
}

views/site/addAlbum.php
<?php
use yii\helpers\Html;
use kartik\widgets\Select2;

$this->title = "Adding Album";

$this->registerCssFile('@web/css/bootstrap-fileinput-master/css/fileinput.css');
$this->registerJsFile('@web/css/bootstrap-fileinput-master/js/plugins/canvas-to-blob.js');
$this->registerJsFile('@web/css/bootstrap-fileinput-master/js/plugins/sortable.js');
$this->registerJsFile('@web/css/bootstrap-fileinput-master/js/plugins/purify.js');
$this->registerJsFile('@web/css/bootstrap-fileinput-master/js/fileinput.js');
$this->registerJsFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js');

$this->registerCssFile('@web/css/create-pages.css');

?>
<p class='main-text-name'><?= Html::encode($this->title) ?></p>

<div class="form-group">
    <div class="form-album">
        <?php
        echo Html::tag('label', Yii::t('app', 'Album Name:'), ['class' => 'control-label']);
        ?>
        <div>
            <?php
            echo Html::tag('span', Yii::t('app', 'You can input new name for album only.'), ['class' => 'small pull-left']);
            ?>
        </div>
        <?php
        echo Html::tag('label', Yii::t('app', 'Max 30 symbols.'), ['class' => 'small pull-right text-success', 'id' => 'remain-sym-album']);
        echo Html::input('text', 'album', '', ['class' => 'form-control', 'id' => 'album']);
        ?>
    </div>
    <div class="form-songs">
            <?php
            echo Html::tag('label', Yii::t('app', 'Select Songs:'), ['class' => 'control-label']);
            ?>
            <div>
                <?php
                echo Html::tag('span', Yii::t('app', 'Choose exist songs or create new '), ['class' => 'small']);
                echo Html::a(Yii::t('app', ' here'), '/site/upload-song', ['style' => 'font-size: 85%']);
                ?>
            </div>
            <?php
            echo Select2::widget([
                'name' => 'songs-select',
                'id' => 'songs',
                'data' => $data['songs-list'],
                'disabled' => $data['songs-opt']['disabled'],
                'maintainOrder' => true,
                'options' => ['placeholder' => 'Select songs ...', 'multiple' => true],
                'pluginOptions' => [
                    'tags' => true,
                    'maximumInputLength' => 10
                ],
            ]);
            ?>
    </div>
    <div class="form-avatar">
        <?php
        echo Html::tag('label', Yii::t('app', 'Album Avatar:'), ['class' => 'control-label']);
        ?>
        <div>
            <?php
            echo Html::tag('span', Yii::t('app', 'Extension for image: img,jpeg,png.'), ['class' => 'small pull-left']);
            ?>
        </div>
        <input class="file-loading" id="avatar" name="avatar-input" type="file" data-show-preview="false">
    </div>
    <div>
        <input class="btn btn-success btn-md" id="send" type="submit">
    </div>

    <div id="info"></div>
</div>
<script>
    $(function () {
        $("#album").keyup(function () {
            var album = $("#album");
            var remain = $("#remain-sym-album");
            remain.html("Max " + (30 - album.val().length) + " symbols");
            if ((30 - album.val().length) < 0) {
                remain.removeClass('text-danger text-success').addClass('text-danger');
            } else {
                remain.removeClass('text-success text-danger').addClass('text-success');
            }
        });

        $("#avatar").fileinput({
            maxFileSize: 2000,
            browseClass: "btn btn-success",
            browseLabel: "Pick Avatar",
            previewFileType: "image",
            allowedFileTypes: ["image"],
            allowedFileExtensions: ["png", "jpeg", "jpg"],

            previewFileIconSettings: {
                'png': '<i class="fa fa-file-photo-o text-warning"></i>',
                'jpg': '<i class="fa fa-file-photo-o text-warning"></i>'
            },
            previewFileExtSettings: {
                'png': function (ext) {
                    return ext.match(/(png|jpeg)$/i);
                },
                'jpg': function (ext) {
                    return ext.match(/(jpg)$/i);
                }
            },
            overwriteInitial: false,
            initialCaption: "Choose avatar...",
            showUpload: false
        });
        $("#send").click(function () {
            var album = $("#album").val();
            var avatar = $("#avatar");
            var songs = JSON.stringify($("#songs").val());

            var form = new FormData();
            $.each(avatar[0].files, function (key, value) {
                form.append("avatar", value);
            });
            console.log(songs);
            form.append("album_name", album);
            form.append("songs", songs);

            $("p.alert-success").remove();
            $("p.alert-danger").remove();

            $.ajax({
                url: "/save/save-album",
                data: form,
                type: "post",
                cache: false,
                contentType: false,
                processData: false
            }).done(function (response) {
                response = JSON.parse(response);
                console.log(response);
                if (response.result) {
                    $(".form-group").append("<p class='alert alert-success'>" + response.content + "</p>");
                    console.log(response.content);
                } else {
                    $(".form-group").append("<p class='alert alert-danger'>" + response.content + "</p>");
                    console.log(response.content);
                }
                setTimeout(
                    function () {
                        $('.alert').fadeOut('fast');
                    }, 3000);
            }).fail(function (error) {
                console.log(error.responseText);
            });
        });
    })
</script>

views/site/addNews.php
<?php
use yii\helpers\Html;
use kartik\widgets\Select2;

$this->title = "Create News";

//$this->registerJsFile('@web/js/add_news.js');

$this->registerCssFile('@web/css/bootstrap-fileinput-master/css/fileinput.css');
$this->registerJsFile('@web/css/bootstrap-fileinput-master/js/plugins/canvas-to-blob.js');
$this->registerJsFile('@web/css/bootstrap-fileinput-master/js/plugins/sortable.js');
$this->registerJsFile('@web/css/bootstrap-fileinput-master/js/plugins/purify.js');
$this->registerJsFile('@web/css/bootstrap-fileinput-master/js/fileinput.js');
$this->registerJsFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js');

$this->registerCssFile('@web/css/create-pages.css');

?>
<table border="0" align="center">
    <p class='main-text-name'><?= Html::encode($this->title) ?></p>
    <div class="form-group">
        <div class="form-category">
            <?php
            echo Html::tag('label', Yii::t('app', 'Category:'), ['class' => 'control-label']);
            ?>
            <div>
                <?php
                echo Html::tag('span', Yii::t('app', 'Choose exist category or create new '), ['class' => 'small']);
                echo Html::a(Yii::t('app', ' here'), '/site/add-category', ['style' => 'font-size: 85%']);
                ?>
            </div>
            <?php
            echo Select2::widget([
                'name' => 'category-select',
                'id' => 'category',
                'data' => $data['category-list'],
                'disabled' => $data['category-opt']['disabled'],
                'options' => ['placeholder' => 'Select categories ...'],
                'pluginOptions' => [
                    'tags' => true,
                    'tokenSeparators' => [',', ' '],
                    'maximumInputLength' => 10
                ],
            ]);
            ?>
        </div>

        <div class="form-author">
            <?php
            echo Html::tag('label', Yii::t('app', 'Author:'), ['class' => 'control-label']);
            ?>
            <div>
                <?php
                echo Html::tag('span', Yii::t('app', 'Choose exist author or create new'), ['class' => 'small']);
                echo Html::a(Yii::t('app', ' here'), '/site/add-author', ['style' => 'font-size:85%']);
                ?>
            </div>
            <?php
            echo Select2::widget([
                'name' => 'author-select',
                'id' => 'author',
                'data' => $data['authors-list'],
                'disabled' => $data['authors-opt']['disabled'],
                'options' => ['placeholder' => 'Select authors ...'],
                'pluginOptions' => [
                    'tags' => true,
                    'tokenSeparators' => [',', ' '],
                    'maximumInputLength' => 10
                ],
            ]);
            ?>
        </div>
        <div class="form-tags">
            <?php
            echo Html::tag('label', Yii::t('app', 'Tags:'), ['class' => 'control-label']);
            ?>
            <div>
                <?php
                echo Html::tag('span', Yii::t('app', 'Choose exist tags or create new here'), ['class' => 'small']);
                ?>
            </div>
            <?php
            echo Select2::widget([
                'name' => 'tags-select',
                'id' => 'tags',
                'data' => $data['tags-list'],
                'maintainOrder' => true,
                'options' => ['placeholder' => 'Select tags ...', 'multiple' => true],
                'pluginOptions' => [
                    'tags' => true,
                    'maximumInputLength' => 10
                ],
            ]);
            ?>
        </div>
        <div class="form-songs">
            <?php
            echo Html::tag('label', Yii::t('app', 'Songs:'), ['class' => 'control-label']);
            ?>
            <div>
                <?php
                echo Html::tag('span', Yii::t('app', 'Choose exist songs or create new '), ['class' => 'small']);
                echo Html::a(Yii::t('app', ' here'), '/site/upload-song', ['style' => 'font-size:85%']);
                ?>
            </div>
            <?php
            echo Select2::widget([
                'name' => 'songs-select',
                'id' => 'songs',
                'data' => $data['songs-list'],
                'disabled' => $data['songs-opt']['disabled'],
                'maintainOrder' => true,
                'options' => ['placeholder' => 'Select songs ...', 'multiple' => true],
                'pluginOptions' => [
                    'tags' => true,
                    'maximumInputLength' => 10
                ],
            ]);
            ?>
        </div>

        <div class="form-picture">
            <?php
            echo Html::tag('label', Yii::t('app', 'Picture:'), ['class' => 'control-label']);
            ?>
            <div>
                <?php
                echo Html::tag('span', Yii::t('app', 'Upload your avatar for new.'), ['class' => 'small']);
                ?>
            </div>
            <input class="file-loading" id="avatar-input" name="avatar-input" type="file" data-show-preview="false">
        </div>

        <div class="form-title">
            <?php
            echo Html::tag('label', Yii::t('app', 'Title:'), ['class' => 'control-label']);
            ?>
            <div>
                <?php
                echo Html::tag('span', Yii::t('app', 'Input title for news for display on news page.'), ['class' => 'small pull-left']);
                ?>
            </div>
            <?php
            echo Html::tag('label', Yii::t('app', 'remain 50 symbols'), ['class' => 'control-label pull-right text-success', 'id' => 'remain-sym-title']);
            ?>
            <input class="form-control" id="title" type="text" placeholder="Input title...">
        </div>

        <div class="form-content">
            <?php
            echo Html::tag('label', Yii::t('app', 'Content:'), ['class' => 'control-label']);
            ?>
            <div>
                <?php
                echo Html::tag('span', Yii::t('app', 'Input content of songs for more details.'), ['class' => 'small pull-left']);
                ?>
            </div>
            <?php
            echo Html::tag('label', Yii::t('app', 'remain 255 symbols'), ['class' => 'control-label pull-right text-success', 'id' => 'remain-sym-content']);
            ?>
            <textarea class="form-control" id="content" rows="5" placeholder="Comment..."></textarea>
        </div>
        <div class="col-lg-12 text-center">
            <input class="btn btn-success btn-md" id="send" type="submit" value="submit">
        </div>
    </div>
</table>

<script>

    $("#content").keyup(function () {
        var content = $("#content");
        var maxTextContent = 255;
        var remainContent = $("#remain-sym-content");


        remainContent.html("remain " + (maxTextContent - content.val().length) + " symbols");
        if ((maxTextContent - content.val().length) < 0) {
            remainContent.removeClass('text-danger text-success').addClass('text-danger');
        } else {
            remainContent.removeClass('text-success text-danger').addClass('text-success');
        }
    });

    $("#title").keyup(function () {
        var title = $("#title");
        var maxTextTitle = 50;
        var remainTitle = $("#remain-sym-title");
        remainTitle.html("remain " + (maxTextTitle - title.val().length) + " symbols");
        if ((maxTextTitle - title.val().length) < 0) {
            remainTitle.removeClass('text-danger text-success').addClass('text-danger');
        } else {
            remainTitle.removeClass('text-success text-danger').addClass('text-success');
        }
    });
    $(document).ready(function () {

        $("#avatar-input").fileinput({
            maxFileSize: 2000,
            browseClass: "btn btn-success",
            browseLabel: "Pick Avatar",
            previewFileType: "image",
            allowedFileTypes: ["image"],
            allowedFileExtensions: ["png", "jpeg", "jpg"],

            previewFileIconSettings: {
                'png': '<i class="fa fa-file-photo-o text-warning"></i>',
                'jpg': '<i class="fa fa-file-photo-o text-warning"></i>',
            },
            previewFileExtSettings: {
                'png': function (ext) {
                    return ext.match(/(png|jpeg)$/i);
                },
                'jpg': function (ext) {
                    return ext.match(/(jpg)$/i);
                }
            },
            overwriteInitial: false,
            initialCaption: "Choose avatar...",
            showUpload: false

        });


        $("#send").click(function () {
            var category = $("#category").val();
            var author = $("#author").val();
            var tags = JSON.stringify($("#tags").val());
            var songs = JSON.stringify($("#songs").val());
            var avatar = $("#avatar-input");
            var title = $("#title").val();
            var content = $("#content").val();

            var form = new FormData();
            $.each(avatar[0].files, function (key, value) {
                form.append("avatar", value);
            });
            form.append("category", category);
            form.append("author", author);
            form.append("tags", tags);
            form.append("songs", songs);
            form.append("avatar", avatar);
            form.append("title", title);
            form.append("content", content);

            $("p.alert-success").remove();
            $("p.alert-danger").remove();
            $.ajax({
                url: "/save/save-news",
                data: form,
                type: "post",
                cache: false,
                contentType: false,
                processData: false
            }).done(function (response) {
                response = JSON.parse(response);
                console.log(response);
                if (response.result) {
                    $(".form-group").append("<p class='alert alert-success'>" + response.content + "</p>");
                    console.log(response.content);
                } else {
                    $(".form-group").append("<p class='alert alert-danger'>" + response.content + "</p>");
                    console.log(response.content);
                }
                setTimeout(
                    function () {
                        $('.alert').fadeOut('fast');
                    }, 3000);
            }).fail(function (error) {
                console.log(error.responseText);
            });
        });
    });
</script>

views/site/author.php
<?php
$this->title = "Author page";

$this->registerJsFile('@web/js/sendMusic.js');
$this->registerJsFile('@web/js/page_author.js');
use yii\helpers\Html;
?>
<div id="music">
    <p class='main-text-name'><?= Html::encode($this->title)?></p>

    <font size="10">{$author}</font><br>

    <br><br><br>
</div>

views/site/debug.php
<?php
use yii\helpers\Html;

$this->title = "Debug page";
//$this->registerJsFile('@web/js/debug');

?>
<div class="right-side-cont">
    <p class='main-text-name'><?= Html::encode($this->title) ?></p>

    <div id="info"></div>
</div>
<script>

</script>

views/site/delete.php
<?php
use yii\helpers\Html;
use kartik\widgets\Select2;

$this->title = "Delete page";

$this->registerJsFile('@web/js/select2/dist/js/select2.full.js');
$this->registerCssFile('@web/js/select2/dist/css/select2.css');
//$this->registerJsFile('@web/js/page_delete.js');
$this->registerCssFile('@web/css/delete.css');

?>
<p class='main-text-name'><?= Html::encode($this->title) ?></p>

<div class="form-group">
    <div class="form-news">
        <?php
        echo Html::tag('label', Yii::t('app', 'Select News:'), ['class' => 'control-label']);
        ?>
        <div>
            <?php
            echo Html::tag('span', Yii::t('app', 'Choose exist news or create new '), ['class' => 'small']);
            echo Html::a(Yii::t('app', ' here'), '/site/add-news', ['style' => 'font-size: 85%']);
            ?>
        </div>
        <?php
        echo Select2::widget([
            'name' => 'news-select',
            'id' => 'news',
            'data' => $data['news-list'],
            'disabled' => $data['news-opt']['disabled'],
            'options' => ['placeholder' => 'Select categories ...', 'multiple' => true],
            'pluginOptions' => [
                'tags' => true,
                'tokenSeparators' => [',', ' '],
                'maximumInputLength' => 10
            ],
        ]);
        ?>
        <input class="btn btn-success btn-md" id="delete-news" type="button" value="Delete"
               onclick="Delete($('.form-news'))">
    </div>
    <hr>
    <div class="form-category">
        <?php
        echo Html::tag('label', Yii::t('app', 'Select Category:'), ['class' => 'control-label']);
        ?>
        <div>
            <?php
            echo Html::tag('span', Yii::t('app', 'Choose exist category or create new '), ['class' => 'small']);
            echo Html::a(Yii::t('app', ' here'), '/site/add-category', ['style' => 'font-size: 85%']);
            ?>
        </div>
        <?php
        echo Select2::widget([
            'name' => 'category-select',
            'id' => 'category',
            'data' => $data['category-list'],
            'disabled' => $data['category-opt']['disabled'],
            'options' => ['placeholder' => 'Select categories ...', 'multiple' => true],
            'pluginOptions' => [
                'tags' => true,
                'maximumInputLength' => 10
            ],
        ]);
        ?>
        <input class="btn btn-success btn-md" id="delete-categories" type="button" value="Delete"
               onclick="Delete($('.form-category'))">
    </div>
    <hr>
    <div class="form-albums">
        <?php
        echo Html::tag('label', Yii::t('app', 'Select Albums:'), ['class' => 'control-label']);
        ?>
        <div>
            <?php
            echo Html::tag('span', Yii::t('app', 'Choose exist albums or create new '), ['class' => 'small']);
            echo Html::a(Yii::t('app', ' here'), '/site/add-album', ['style' => 'font-size: 85%']);
            ?>
        </div>
        <?php
        echo Select2::widget([
            'name' => 'album-select',
            'id' => 'album',
            'data' => $data['album-list'],
            'disabled' => $data['album-opt']['disabled'],
            'maintainOrder' => true,
            'options' => ['placeholder' => 'Select album ...', 'multiple' => true],
            'pluginOptions' => [
                'tags' => true,
                'maximumInputLength' => 10
            ],
        ]);
        ?>
        <input class="btn btn-success btn-md" id="delete-albums" type="button" value="Delete"
               onclick="Delete($('.form-albums'))">

    </div>
    <hr>
    <div class="form-songs">
        <?php
        echo Html::tag('label', Yii::t('app', 'Select Songs:'), ['class' => 'control-label']);
        ?>
        <div>
            <?php
            echo Html::tag('span', Yii::t('app', 'Choose exist songs or create new '), ['class' => 'small']);
            echo Html::a(Yii::t('app', ' here'), '/site/upload-song', ['style' => 'font-size: 85%']);
            ?>
        </div>
        <?php
        echo Select2::widget([
            'name' => 'songs-select',
            'id' => 'songs',
            'data' => $data['songs-list'],
            'disabled' => $data['songs-opt']['disabled'],
            'maintainOrder' => true,
            'options' => ['placeholder' => 'Select songs ...', 'multiple' => true],
            'pluginOptions' => [
                'tags' => true,
                'maximumInputLength' => 10
            ],
        ]);
        ?>
        <input class="btn btn-success btn-md" id="delete-songs" type="button" value="Delete"
               onclick="Delete($('.form-songs'))">
    </div>
    <hr>
</div>
<div id="infoByButton"></div>
<script>
    function Delete(tag) {
        var data = tag.find('select').val();
        var url = tag.find('input')[1].id;
        $.post("/delete/" + url, {
                data: data
            },
            function (data) {
                data = JSON.parse(data);
                message = tag.find("p.delete-message");
                message.remove();
                if(data.result){
                    tag.append("<p class='alert-success delete-message'>" + data.message + "</p>");
                }else{
                    tag.append("<p class='alert-danger delete-message'>" + data.message + "</p>");
                }
                setTimeout(function () {
                    tag.find("p.delete-message").remove();
                },3000)
            }
        );
    }
</script>

views/site/registration.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->registerJsFile('@web/js/reglog.js');
$this->title = "Registration";
?>
<div id="divRegister">
    <p class='main-text-name'><?= Html::encode($this->title)?></p>

    <div class='form-group-sm col-lg-10'>
        <?php $form = ActiveForm::begin([
            'id'=>'registration-form',
            'options' => [
                'class' => 'col-lg-10',
            ],

            'layout' => 'horizontal',
            'fieldConfig' => [
                'horizontalCssClasses' => [
                    'label' => 'col-lg-4',
                ],
                'template' => "<div class='col-lg-5'>{label}</div><div class='col-lg-8'>{input}</div>\n<div class='col-lg-8'>{error}</div>",
                'labelOptions' => ['class'=>'col-lg-12 control-panel'],

            ]
        ])?>

        <?= $form->field($model,'username')->textInput(['autofocus'=>true]);?>
        <?= $form->field($model,'password')->passwordInput();?>
        <?= $form->field($model,'re_password')->passwordInput();?>
        <?= $form->field($model,'email')->textInput();?>
        <?= Html::submitButton('Submit',['id'=>'Register','class'=>'btn btn-primary col-lg-3','action'=>'/site/search']);?>
        <?php ActiveForm::end();?>
    </div>
</div>